### ISSUE TITLE
 训练得不到结果 Unable to receive training

### ISSUE THREAD

**Issue by zuodazuoqiangzaichuanghuihuang** [Pyxel970524/GPR-Clutter-Removal#1]
Sorry, using the blogger's code for training and making predictions cannot obtain the paper results? Is there a solution?
![Figure_1](https://github.com/Pyxel970524/GPR-Clutter-Removal/assets/126548542/39a25460-404a-471c-884c-8d4f3c76226f)

**Comment by Pyxel0524** [comment]
The parameters during training should be modified according to the paper. I have updated the train.py file, and you can try again

**Comment by zuodazuoqiangzaichuanghuihuang** [comment]
[Train - 副本 (2).txt](https://github.com/Pyxel970524/GPR-Clutter-Removal/files/12028040/Train.-.2.txt)
大佬，新上传的代码和原来代码训练的效果不大，还是不能得到论文效果，我只修改了数据路径等，得不到效果是因为我没有修改更新策略吗？似乎大佬上传的代码中的scheduler没有使用？

**Comment by Pyxel0524** [comment]
> Author

前段时间比较忙，我最近检查了下好像没问题，不过我的实验是在colab上进行训练的，不知道有没有影响。我分享了我训练好的模型，你可以拿去试试。

**Comment by nxihdbjna** [comment]
您好，我下载不了您的Pretrain model，以至于里面的一些路径改不了，可以再发一下吗，或者给我说一下原因吗？谢谢

**Comment by nxihdbjna** [comment]
您好，T_PowerGain这个模块的代码可以共享一下吗，谢谢

**Comment by ambglh** [comment]
你好，zuodazuoqiangzaichuanghuihuang。我训练完也是输出这样的结果，请问你现在解决了吗

**Comment by nxihdbjna** [comment]
不好意思，没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月29日(周六) 下午4:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Pyxel0524/GPR-Clutter-Removal]  训练得不到结果 Unable to receive training (Issue #1)




 
你好，zuodazuoqiangzaichuanghuihuang。我训练完也是输出这样的结果，请问你现在解决了吗
